powDat<-read.table("household_power_consumption.txt", header=T, sep=";")
day1<-subset(powDat, Date=="1/2/2007")
day2<-subset(powDat, Date=="2/2/2007")
plotDat<-rbind(day1,day2)
library(lubridate)
datetime<-dmy(as.vector(plotDat[,1]))+hms(as.vector(plotDat[,2]))
plotDat<-cbind(plotDat,datetime)
png('Plot3.png')
plot(plotDat$datetime,as.numeric(plotDat$Sub_metering_1), type="n",xlab="",ylab="Energy sub metering")
lines(plotDat$datetime, as.numeric(plotDat$Sub_metering_1))
lines(plotDat$datetime, as.numeric(plotDat$Sub_metering_2),  col="red")
lines(plotDat$datetime, as.numeric(plotDat$Sub_metering_3), col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),lwd=c(1,1,1),col=c("black","red","blue"))
dev.off()