powDat<-read.table("household_power_consumption.txt", header=T, sep=";")
day1<-subset(powDat, Date=="1/2/2007")
day2<-subset(powDat, Date=="2/2/2007")
plotDat<-rbind(day1,day2)
library(lubridate)
datetime<-dmy(as.vector(plotDat[,1]))+hms(as.vector(plotDat[,2]))
plotDat<-cbind(plotDat,datetime)
png('Plot2.png')
plot(plotDat$datetime,as.numeric(plotDat$Global_active_power)/500, type="n",xlab="",ylab="Global Active Power (Killowatts)")
lines(plotDat$datetime, as.numeric(plotDat$Global_active_power)/500,  lwd=1.5)
dev.off()